### PR TITLE
Fix modmenu integration

### PR DESCRIPTION
**Pull request by LostLuma**
Makes the config edit button actually show up in modmenu so users can activate the pride setting.

### CODE REVIEW

**Comment by triphora** [comment]
This should be done automatically as long as you have [a new enough MidnightLib version](https://modrinth.com/mod/midnightlib/version/0.6.1).

**Comment by LostLuma** [comment]
It doesn't work for me with the version you linked, and the [midnightlib docs](https://github.com/TeamMidnightDust/MidnightLib/wiki/Using-MidnightConfig) state that you still need to implement this yourself at the bottom of the page.

**Comment by triphora** [comment]
Huh, it should be automatic according to https://github.com/TeamMidnightDust/MidnightLib/blob/main/src/main/java/eu/midnightdust/lib/config/AutoModMenu.java. @Motschen any idea why it might not be working?

**Comment by Motschen** [comment]
Yeah, MidnightLib should automatically register the config screen to mod menu, the code at the bottom of the documentation is just an example on how to get an instance of the screen for usage in other mods and custom GUIs, I'll make that more clear.

Could you please set "Config Screen List" in MidnightLib's config to True and tell me if Quilt Loading Screen appears in the new menu that gets added to the Options Screen?

**Comment by LostLuma** [comment]
Setting it to `True` instead of `ModMenu` makes a new button show up in the settings menu that works, yeah.

**Comment by Motschen** [comment]
And is Quilt Loading Screen listed in there?

**Comment by LostLuma** [comment]
Yes.

**Comment by Motschen** [comment]
And it still doesn't show up in ModMenu?

**Comment by Motschen** [comment]
Could you tell me if the config button in ModMenu appears for any other mod using MidnightLib, for example https://modrinth.com/mod/cull-leaves ?

**Comment by LostLuma** [comment]
The button for the leave culling mod does show up correctly within modmenu, quilt loading screen still doesn't.

**Comment by Motschen** [comment]
That's really weird...
I tried every single mod using MidnightLib, and Quilt Loading Screen is the only one the ModMenu integration doesn't work for.
At first I assumed it was caused by it using a quilt.mod.json, but Music Duration Reducer does too and it works there.
Not really sure what's going on here, I'll definitely look into it further.
For now it might be best to merge this PR.

**Comment by triphora** [comment]
If you say so!

**Comment by Motschen** [comment]
Oh, right, I figured it out, the reason is actually pretty simple: The actual mod id differs from the one you use internally, thus AutoModMenu can't map the config screen to the mod:
https://github.com/emmods/quilt-loading-screen/blob/1.19/src/main/java/coffee/waffle/qls/QuiltLoadingScreen.java#L25
https://github.com/emmods/quilt-loading-screen/blob/1.19/src/main/resources/quilt.mod.json#L5
In this case you'll have to implement the ModMenu integration by yourself, as MidnightLib can't do magic ;)

**Pull request merged**
